FROM ubuntu

MAINTAINER apearl@student.21-school.ru

RUN apt-get update && apt-get upgrade -y && apt-get install -y nodejs npm git vim emacs

RUN npm install yarn --global && npm install npm --global
